telemetry = false

[alias]
"@" = "./src"

# [install]
# production = true

[run]
# default on Windows
bun = true
# shell = "bun"
silent = false

[install.scopes]
"@phederal" = { url = "https://npm.pkg.github.com/", token = "$NPM_CONFIG_TOKEN" }
