name: Publish to npm
on:
  workflow_dispatch:    # позволяет запуск вручную
  release:
    types: [published]  # и автоматически при создании релиза

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install & Build
        run: |
          bun install

      - name: Publish via Bun
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_CONFIG_TOKEN}" > ~/.npmrc
          bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
