name: Publish package with build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write # для GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install TypeScript
        run: bun add -d typescript

      - name: Install deps
        run: bun install

      - name: Build package
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-gh:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Setup Node for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
          scope: "@phederal"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Ensure @phederal scope in package.json
        run: |
          jq '.name = "@phederal/socket.io-bun"' package.json > package-github.json
          mv package-github.json package.json

      - name: Create .npmrc for GitHub Packages
        run: |
          echo "@phederal:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: bun publish

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Setup Bun for npmjs.org
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Strip GitHub publishConfig
        run: sed -i '/"publishConfig":/,/}/d' package.json

      - name: Install deps
        run: bun install

      - name: Create .npmrc for npmjs
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npmjs.org
        run: bun publish --access public --registry https://registry.npmjs.org/
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
